### ISSUE TITLE
Implement continuous deployment component

### ISSUE THREAD

**Issue by eistrati** [MitocGroup/run-jst#10]
Continuous deployment process must automatically trigger `deepify deploy` (or something alike) on Github PRs specifically dedicated to deployments. Here below is what we should expect:

1. On "Open PR" to `dev branch` would trigger `deepify deploy --env=dev` and replace existing `dev environment` (ideally using blue-green deployment approach)
2. Similar approaches should be used for `test branch`, `stage branch`, and even `master branch`
3. Sometimes parallel PRs on the same branch could be opened, therefore some kind of locking process must be implemented to avoid useless deployments
4. If automated testing fails (could be unit testing, functional testing, end to end testing, etc), revert back to previous environment (ideally using blue-green deployment approach)
5. To be discussed when we should automatically remove failed environments, because there are concerns that this process will evolve into something huge and unmanageable really quickly

**Comment by ddimitrioglo** [comment]
**Continuous deployment process plan**:

1. For non-blocking development none of PR to dev won't trigger deployment process;
2. PR from dev => dev-e2e triggers deployment process;
     - Set environment specific variables: `ENV=dev`, `BRANCH=dev-e2e`, `AWS_PROFILE=mitoc_profile`
     - `git clone -b ${BRANCH} git@github.com:MitocGroup/atm.git`
     - `aws s3 sync s3://atm-deploy-assets ./deploy --profile ${AWS_PROFILE}`
     - `sh deploy/prepare.sh atm/src -e ${ENV}` (sync .parameters.json)
     - `cd atm/src && deepify install`
     - `cd ../../ && sh deploy/prepare.sh atm/src -e ${ENV}` (sync auth/unauth roles)
     - `cd atm/plugin && npm install && npm run build-all`
     - `cd ../src && deepify server ./ -s` (moves chunks and static pages into root-microservice)
     - `deepify compile prod ./ --purge`
     - `deepify deploy`
     - Invalidate cloudfront cache
     - Run automated (unit/e2e) tests (when they will be written)
     - If automated testing passed then link new cloudfront with www-${ENV}.adtechmedia.io
     - On any error during the deployment process  - run `deepify undeploy`
3. PR from dev-e2e => stage the process is going to be the same, with differences: 
     - `ENV=stage`, `BRANCH=stage`
4. To avoid downtime in prod we can not use described deployment process (deploy from scratch). We should update existing prod environment and this can add some additional steps:
     - sync .xxxxxxxx.prod.provisioning.json from AWS.S3 bucket
     - replace automated tests with manual health check
     - ...

P.S. Pre-requisites for Travis:
- AWS CLI configured
- Node v6.11 (version which supports deepify compile prod)
- Deepify `npm install deepify -g`;
- MediaInfo library;
- Compass `npm install compass -g && npm install node-compass -g && gem install compass`

P.S.S 
- Described steps are tested on "OS X", so most probably we have to chose "Travis OS X Build Environment"
- Improve `npm run build-all` command to have silent mode;
- Improve `deepify deploy` command to have silent mode (now it asks us `Prepare for production? (Y/N):`);

**Comment by ddimitrioglo** [comment]
As this topic is not related to `run-jst`, I've moved it to ATM repository (https://github.com/MitocGroup/atm/issues/980)

**Comment by AlexanderC** [comment]
See the comment added by @ddimitrioglo
