### ISSUE TITLE
GitHub repository AdTechMedia/adtechmedia-website is either missing from Travis CI or Travis CI Pro

### ISSUE THREAD

**Issue by eistrati** [MitocGroup/run-jst#3]
MitocGroup:adtechmedia-website eugene$ jst configure travis --aws-access-key-id [REPLACED] --aws-secret-access-key [REPLACED] --github-token [REPLACED] --overwrite
🎁  Dumping configuration to /Volumes/Data/Users/eugene/Projects/atm-web/.travis.yml

message: 
  """
    GitHub repository AdTechMedia/adtechmedia-website is either missing from Travis CI or Travis CI Pro.
    Please note that if you are using Travis CI Pro you have to provide GitHub credentials or access token, otherwise please do NOT specify credentials or access token options!
    
    For help menu on configuring Travis Pro credentials or access token run: jst configure travis --help.
    
    See how to setup you GitHub repository https://docs.travis-ci.com/user/getting-started#To-get-started-with-Travis-CI%3A
  """
stack: 
  - Error: GitHub repository AdTechMedia/adtechmedia-website is either missing from Travis CI or Travis CI Pro.
  - Please note that if you are using Travis CI Pro you have to provide GitHub credentials or access token, otherwise please do NOT specify credentials or access token options!
  - 
  - For help menu on configuring Travis Pro credentials or access token run: jst configure travis --help.
  - 
  - See how to setup you GitHub repository https://docs.travis-ci.com/user/getting-started#To-get-started-with-Travis-CI%3A
  -     at pify.then.catch.error (/Volumes/Data/Users/eugene/.nvm/versions/node/v6.10.3/lib/node_modules/run-jst/bin/commands/configure/travis.js:101:29)
  -     at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by AlexanderC** [comment]
Please not that you do NOT have to add either GitHub token or credentials unless you are setting up TravisCI Pro, here's the quote:

_Please note that if you are using Travis CI Pro you have to provide GitHub credentials or access token, otherwise please **do NOT specify credentials or access token** options!_

**Comment by eistrati** [comment]
Verified.
